import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Layout/Header";
import Footer from "@/components/Layout/Footer";
import StoreProvider from "./StoreProvider"
import { ClerkProvider } from "@clerk/nextjs";
import {Toaster} from "react-hot-toast"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Full Stack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ClerkProvider>
        <StoreProvider>
          <body className={inter.className}>
            <Header />
            <main className="px-8">{children}</main>
            <Footer />
            <Toaster />
          </body>
        </StoreProvider>
      </ClerkProvider>
    </html>
  );
}
