// import { Product } from "./types";

// export const Products: Product[] = [
//   {
//     id: 1,
//     title: "Brown Jumper",
//     tagline: "Winter Collection",
//     price: 30,
//     category: "female",
//     image: "/images/fem4.png",
//   },
//   {
//     id: 2,
//     title: "Pink Sleevless",
//     tagline: "Summer Collection",
//     price: 60,
//     category: "female",
//     image: "/images/fem2.png",
//   },
//   {
//     id: 3,
//     title: "Cream Upper",
//     tagline: "New Arrival",
//     price: 120,
//     category: "female",
//     image: "/images/fem3.png",
//   },
//   {
//     id: 4,
//     title: "MiniBan Jacket",
//     tagline: "New Arrival",
//     price: 140,
//     category: "male",
//     image: "/images/male2.png",
//   },
//   {
//     id: 5,
//     title: "Grey Trouser",
//     tagline: "All Outfit Dress",
//     price: 150,
//     category: "male",
//     image: "/images/male3.png",
//   },
//   {
//     id: 6,
//     title: "Skin Tight Pent",
//     tagline: "Casual Dress",
//     price: 165,
//     category: "male",
//     image: "/images/male4.png",
//   },
//   {
//     id: 7,
//     title: "Pink Shirt & Trouser",
//     tagline: "Night & Running Dress",
//     price: 180,
//     category: "kids",
//     image: "/images/male1pink.png",
//   },
//   {
//     id: 8,
//     title: "Royal Black Jumper",
//     tagline: "Winter Collection",
//     price: 240,
//     category: "kids",
//     image: "/images/fem5.png",
//   },
//   {
//     id: 9,
//     title: "Silver Jursey",
//     tagline: "New Arrival",
//     price: 280,
//     category: "kids",
//     image: "/images/fem6.png",
//   },
// ];
